services:
  syncthing:
    image: syncthing/syncthing
    container_name: storage
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Warsaw
      - SYNCTHING_STORAGE_URL=${SYNCTHING_STORAGE_URL}
      - SYNCTHING_DIRECTORY=${SYNCTHING_DIRECTORY}
    volumes:
      - ${SYNCTHING_STORAGE_URL}:/var/syncthing
      - ./entry.sh:/entry.sh
    ports:
      # Web interface
      - 8384:8384 
      # File transfer
      - 22000:22000/tcp 
      # File transfer
      - 22000:22000/udp 
      # Discovery
      - 21027:21027/udp 
    restart: unless-stopped
    entrypoint: ["/bin/sh", "/entry.sh"]
  filebrowser:
    image: filebrowser/filebrowser
    container_name: storage-browser
    ports:
      # Web interface
      - 8385:80
    volumes:
      - ${SYNCTHING_STORAGE_URL}:/var/syncthing
    command: ["--root", "/var/syncthing/${SYNCTHING_DIRECTORY}"]
    restart: unless-stopped
