apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vaultsync-server
spec:
  rules:
    - host: vaultsync.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: vaultsync-server
                port:
                  number: 80
